apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  labels:
    app: postgres
spec:
  storageClassName: localnfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
